#!/usr/bin/env node

console.log('Deploying to KMR...');

var exec = require('child_process').exec;
var cmd = 'kinvey-dlc-cli deploy -e mjsalinger+ci@kinvey.com -p k1nv3y';

exec(cmd, function(error, stdout, stderr) {
  console.log(stdout);
});
