#!/usr/bin/env node

console.log('Deploying to KMR...');

var exec = require('child_process').exec;

exec('kinvey-dlc-cli deploy -e mjsalinger+ci@kinvey.com -p k1nv3y', function(error, stdout, stderr) {
	console.log("inside cmd response");
	if(error) { 
		console.log("error: " + error);
		process.exit(1);
	}

	console.log("response: " + stdout);
	console.log("stderr: " + stderr);
  	process.exit(0);
});
